# NAME: rules_routing config for Shadowrocket
# AUTHOR: RomanAverin
# REPO: https://github.com/RomanAverin/shadowrocket-config

[General]
bypass-system = true 
skip-proxy = 127.0.0.1, 192.168.0.0/16, 10.0.0.0/8, 172.16.0.0/12, localhost, *.local
bypass-tun = 10.0.0.0/8, 100.64.0.0/10, 127.0.0.0/8, 169.254.0.0/16, 172.16.0.0/12, 192.0.0.0/24, 192.0.2.0/24, 192.88.99.0/24, 192.168.0.0/16, 198.18.0.0/15, 198.51.100.0/24, 203.0.113.0/24, 224.0.0.0/4, 255.255.255.255/32
dns-server = https://dns.alidns.com/dns-query, system
update-url = https://raw.githubusercontent.com/RomanAverin/shadowrocket-config/main/rules_routing.conf interval=60 strict=true

[DNS]
server=/ru/77.88.8.8
server=/xn--p1ai/77.88.8.8
server=/yandex.com/77.88.8.8
server=/yandex.net/77.88.8.8
server=/yastatic.net/77.88.8.8
server=/vk.com/77.88.8.8
server=/userapi.com/77.88.8.8

#Здесь назначается название для групп прокси, слева название группы, справа название подключения.
#Назовите ваше VPN-подключение, например "NL", тогда оно попадет в группу "NL" и будет использовано в списках правил ниже.
[Proxy Group]
NL = select,NL
US = select,US
RU = select,RU

#Через запятую укажите подкючение из списка прокси выше.
[Rule]
RULE-SET,https://raw.githubusercontent.com/RomanAverin/shadowrocket-config/main/REJECT.list,REJECT
RULE-SET,https://raw.githubusercontent.com/RomanAverin/shadowrocket-config/main/NORU.list,NL
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/Apple/Apple.list,DIRECT
RULE-SET,https://raw.githubusercontent.com/Master-Yoba/shadowrocket-rules/release/rules-geosite/geosite-category-ru.list,DIRECT
RULE-SET,https://raw.githubusercontent.com/RomanAverin/shadowrocket-config/main/RUSSIA.list,DIRECT
#RULE-SET,https://raw.githubusercontent.com/RomanAverin/shadowrocket-config/main/GOOGLE.list,RU

RULE-SET,https://raw.githubusercontent.com/Master-Yoba/shadowrocket-rules/release/rules-geoip/geoip-ru.list,DIRECT
GEOIP,RU,DIRECT
FINAL,PROXY

[URL Rewrite]
^https://(www.)?yandex.ru https://ya.ru 302
